### ISSUE TITLE
git clone 报错

### ISSUE THREAD

**Issue by jonzha9527** [pure-admin/pure-admin-doc#3]
```
Resolving deltas: 100% (14189/14189), done.
error: invalid path 'docs/.vuepress/public/img/type/com1.jpg'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```
> 本地路径中没有中文，git也没有问题， 其他 仓库都可以正常clone

**Comment by xiaoxian521** [comment]
你可以直接点下载
<img width="1517" alt="image" src="https://user-images.githubusercontent.com/44761321/225515226-b09da3a6-ca98-4e62-be47-588f15c8b26b.png">

**Comment by jonzha9527** [comment]
com1, com2 是Windows 保留字，下载文件也是没有用的，只能另存为其他名字，所以才会报错：
error: invalid path 'docs/.vuepress/public/img/type/com1.jpg'
我在macOS 下面就不存在这个问题，建议还是换个文件名把，多数人还是用的Windows
